blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/Artemonim/LittleTools/blob/master/README.MD
    about: Read the project documentation and setup instructions
  - name: 💬 Discussions
    url: https://github.com/Artemonim/LittleTools/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📧 Direct Contact
    url: https://t.me/Artemonim
    about: Contact the developer directly via Telegram for urgent matters 