name: Question
description: Ask a question about LittleTools usage, setup, or functionality
title: "[QUESTION] "
labels: ["question", "needs-response"]
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              Thanks for your question! Please provide as much detail as possible so we can help you effectively. You can fill it in English or Russian.

    - type: checkboxes
      id: checklist
      attributes:
          label: Pre-submission Checklist
          description: Please confirm you have completed these steps
          options:
              - label: I have searched existing issues and discussions for similar questions
                required: true
              - label: I have read the [README.md](../README.md) and relevant documentation
                required: true
              - label: This is not a bug report (use Bug Report template for bugs)
                required: true
              - label: This is not a feature request (use Feature Request template for new features)
                required: true

    - type: dropdown
      id: category
      attributes:
          label: Question Category
          description: What type of question is this?
          options:
              - Installation/Setup help
              - Usage/How-to question
              - Configuration question
              - Performance/Optimization question
              - Compatibility question
              - Development/Contributing question
              - Documentation clarification
              - General question
              - Other
      validations:
          required: true

    - type: dropdown
      id: tool
      attributes:
          label: Related Tool/Component (if applicable)
          description: Which LittleTools component is your question about?
          options:
              - littletools-video (video processing tools)
              - littletools-txt (text processing tools)
              - littletools-speech (speech/audio tools)
              - littletools-cli (main menu system)
              - littletools-core (core utilities)
              - Setup/Installation (starting script)
              - General project question
              - Multiple components
              - Not sure/Not applicable

    - type: textarea
      id: expected
      attributes:
          label: Expected Outcome
          description: What result are you hoping to achieve?
          placeholder: |
              Describe your goal.

    - type: textarea
      id: question
      attributes:
          label: Your Question
          description: What would you like to know? Be as specific as possible.
      validations:
          required: true
