[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "littletools-video"
version = "0.1.0"
description = "Video processing tools for the LittleTools suite."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Pillow>=9.0.0",  # * Image processing library
    # * Depends on the core utilities distributed as a separate package within the workspace.
    # * Since 'littletools-core' is installed in editable mode by the setup script, a normal
    # * package reference is sufficient and avoids path-resolution issues on Windows.
    "littletools-core",
    "typer[all]>=0.9.0",
    "tqdm",
    "opencv-python",
]

[project.scripts]
ffmpeg-normalizer = "littletools_video.FFMPEG_MKV_audio_normalizer:main"
topaz-merger = "littletools_video.Topaz_Video_Merger:main"
video-converter = "littletools_video.video_converter:main"
image-audio-to-video = "littletools_video.Image_Audio_To_Video:main"

[project.entry-points."littletools.commands"]
video-converter = "littletools_video.video_converter:app"
ffmpeg-normalizer = "littletools_video.FFMPEG_MKV_audio_normalizer:app"
topaz-merger = "littletools_video.Topaz_Video_Merger:app"
image-audio-to-video = "littletools_video.Image_Audio_To_Video:app"

[tool.setuptools.packages.find]
where = ["."] 