"""
    --- AUTO-GENERATED DOCSTRING ---
    This docstring is automatically generated by Agent Docstrings.
    Do not modify this block directly.

    Classes/Functions:
    - ObjectInfo (line 16):
      - poke() -> None (line 25)
      - unpoke() -> None (line 28)
      - __hash__() (line 31)
      - __eq__(other) (line 34)
      - __repr__() (line 39)
    --- END AUTO-GENERATED DOCSTRING ---
--- AUTO-GENERATED DOCSTRING ---
This docstring is automatically generated by Agent Docstrings.
Do not modify this block directly.

Classes/Functions:
- ObjectInfo (line 13):
  - poke() -> None (line 22)
  - unpoke() -> None (line 25)
  - __hash__() (line 28)
  - __eq__(other) (line 31)
  - __repr__() (line 36)
--- END AUTO-GENERATED DOCSTRING ---
"""


class ObjectInfo:
    """
    Store meta information for an object
    """

    def __init__(self, id: int):
        self.id = id
        self.poke_count = 0  # count number of detections missed

    def poke(self) -> None:
        self.poke_count += 1

    def unpoke(self) -> None:
        self.poke_count = 0

    def __hash__(self):
        return hash(self.id)

    def __eq__(self, other):
        if type(other) == int:
            return self.id == other
        return self.id == other.id

    def __repr__(self):
        return f"(ID: {self.id})"
